# Network
network_layers: [32, 32, 32]
activiation_fn: "selu"
dropout_rate: 0.25
batch_size: 32
early_stop: True
patience: 5
n_samples_train: 10
n_samples_valid: 10
n_samples_test: 100

optimizer:
  class_name: SGD
  config:
    learning_rate: 0.05
    momentum: 0.9
    decay: 0.001