# Network
network_layers: [64, 128]
activiation_fn: "relu"
dropout_rate: 0.1
l2_reg: 0.0001
batch_size: 32
early_stop: True
patience: 5
n_samples_train: 10
n_samples_valid: 10
n_samples_test: 100

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.001