# Network
network_layers: [32]
activiation_fn: "selu"
dropout_rate: 0.25
batch_size: 32
early_stop: True
patience: 5
n_samples_train: 10
n_samples_valid: 10
n_samples_test: 100

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.01
    momentum: 0
    decay: 0.0001
