# Network
network_layers: [16, 16, 16]
activiation_fn: "selu"
dropout_rate: 0.25
l2_reg: 0.1
batch_size: 128

optimizer:
  class_name: SGD
  config:
    learning_rate: 0.05
    momentum: 0.9
    decay: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None