# Network
network_layers: [64, 64]
activiation_fn: "selu"
dropout_rate: 0.25
l2_reg: 0.1

optimizer:
  class_name: SGD
  config:
    learning_rate: 0.005
    momentum: 0.9
    decay: 0.00001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None