# Network
batch_size: 16
num_epochs: 25
verbose: False
network_layers: [16, 16, 16]
activiation_fn: "relu"
dropout_rate: 0.25

optimizer:
  class_name: Nadam
  config:
    learning_rate: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None