# Network
batch_size: 8
num_epochs: 10
verbose: False
network_layers: [64]
activiation_fn: "relu"
dropout_rate: 0.5
l2_kernel_regularization: 0.1

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.01

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None