# Network
batch_size: 32
num_epochs: 10
verbose: False
network_layers: [64, 64, 64]
activiation_fn: "relu"
dropout_rate: 0.5

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None