# Network
batch_size: 16
num_epochs: 25
verbose: False
network_layers: [16]
activiation_fn: "selu"
dropout_rate: null
l2_kernel_regularization: 0.001

optimizer:
  class_name: Nadam
  config:
    learning_rate: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None