# Network
batch_size: 32
num_epochs: 25
verbose: False
network_layers: [32]
activiation_fn: "selu"
dropout_rate: 0.5

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.01

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None