# Network
network_layers: [32, 32]
activiation_fn: "selu"
dropout_rate: 0.25
l2_reg: 0.1

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None