# Network
batch_size: 16
num_epochs: 25
verbose: False
network_layers: [16, 16, 16]
activiation_fn: "selu"
dropout_rate: 0.25
l2_kernel_regularization: null

optimizer:
  class_name: RMSprop
  config:
    learning_rate: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None